name: "Checkout and install"
description: "Checks out the repo and installs all the yarn dependencies"
inputs:
  ref:
    description: "The ref to check out"
    required: false
runs:
  using: "composite"
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.ref }}
          clean: false

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: get node version
        id: node-version
        run: echo "::set-output name=value::$(node --version)"

      - name: install dependencies
        run: yarn install --frozen-lockfile  --ignore-engines


